# Generated by Django 6.0.2 on 2026-05-19 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtk', models.IntegerField(choices=[(3, 'Tinggi'), (2, 'Sedang'), (1, 'Rendah')])),
                ('indo', models.IntegerField(choices=[(3, 'Tinggi'), (2, 'Sedang'), (1, 'Rendah')])),
                ('ipa', models.IntegerField(choices=[(3, 'Tinggi'), (2, 'Sedang'), (1, 'Rendah')])),
                ('ips', models.IntegerField(choices=[(3, 'Tinggi'), (2, 'Sedang'), (1, 'Rendah')])),
                ('realistic', models.IntegerField()),
                ('investigative', models.IntegerField()),
                ('artistic', models.IntegerField()),
                ('social', models.IntegerField()),
                ('enterprising', models.IntegerField()),
                ('conventional', models.IntegerField()),
                ('logika', models.IntegerField()),
                ('verbal', models.IntegerField()),
                ('mekanikal', models.IntegerField()),
                ('rekomendasi_akademik', models.CharField(max_length=100)),
                ('rekomendasi_riasec', models.CharField(max_length=100)),
                ('rekomendasi_bakat', models.CharField(max_length=100)),
                ('rekomendasi_gabungan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil Tes',
                'verbose_name_plural': 'Hasil Tes',
            },
        ),
    ]
