# Generated by Django 6.0.2 on 2026-05-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hasiltes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasiltes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tes', to=settings.AUTH_USER_MODEL),
        ),
    ]
