# Generated by Django 6.0.2 on 2026-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hasiltes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasiltes',
            name='indo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hasiltes',
            name='ipa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hasiltes',
            name='ips',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hasiltes',
            name='mtk',
            field=models.IntegerField(),
        ),
    ]
