# Generated by Django 6.0.2 on 2026-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hasiltes_indo_alter_hasiltes_ipa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
